- webtranslate/data.py
eints has a lot of duplicated strings, especially when loading
from JSON. For example, every language has a copy of the base-string
it belongs to. Without deduplication, OpenTTD uses ~350MB RAM. With
deduplication this drops to ~280MB RAM, a good 60MB RAM gain.
> Add: use sys.intern() on strings for classes using __slots__

- scripts/filter_update_langs
- webtranslate/utils.py
fc2f4273cc originally implemented #29 as a feature, except it forgot to set the parameter to enable it...
> Fix #29: In the string edit page, display the base string with translated commands.

- scripts/lang_sync
- webtranslate/newgrf/language_file.py
- webtranslate/pages/upload_language.py
Fixes
* When uploading files that exceeded the upload size limit, eints would truncate them, and try to process the rest anyway. (very weird)
* Truncation could result in invalid utf-8 sequences, resulting in status 500.
* The upload script considered uploads successful, when eints redirected to a user-friendly pages listing the problems.
> Improve error checking when uploading translations

- Dockerfile
- docs/manual/string_commands.rst
- requirements.txt
- views/main_template.tpl
- views/root.tpl
- views/string_form.tpl
Links to documentation points to openttdcoop.org (and it's currently down).
As the documentation is generated from eints repo, I think it's a good idea to include it in the image and stop relying on an external location.
> Fix #49: include EINTS manual in the Docker image

- webtranslate/main.py
- webtranslate/pages/root.py
This is a backport from the openttd-github branch.
> Add /healthz endpoint and don't log successful responses

- scripts/lang_sync
- webtranslate/pages/download_list.py
This is a backport from the openttd-github branch.
> Change: List languages with name instead of ISO code in the commit messages.

- views/main_template.tpl
- views/project.tpl
- views/root.tpl
If you are admin, you know those links. They are not useful for anyone else.
Owh, and please don't run eints where you are allowed to just create
projects and languages, that is not secure.
> Remove: admin links from public pages

- .github/workflows/testing.yml
- scripts/eintsgit.py
This is a backport from the openttd-github branch.
This script allows easy export of eints to git, and of git back into eints.
> Glue between eints and git

- rights_example.dat
This is a backport from the openttd-github branch.
This file is actually copied in `Dockerfile`, so it changes how we deploy eints. But it is also a fine example for other people to understand how eints could work.
> Change: enable language creation for all projects, but steam-data.

- webtranslate/pages/string_edit.py
Basically: this feature never worked at all.
> Fix: Translation-hints from related languages showed the text from the current language, not from the related one.

- views/string_form.tpl
- webtranslate/pages/string_edit.py
Mainly a debugging feature, but also nice-to-know for the translator.
> Feature: the string translation history shows exact time-stamps, and which version is committed or pending.

- webtranslate/pages/upload_language.py
```
When syncing translations from git to eints, strings were only tagged as
"committed" if they were unknown to eints, so new translations from eints
were never tagged after the commit.
When translators then updated the translation again, eints would discard
old untagged translation eventually. At that point the next git sync
would consider the old translation in git as newer than the fresh
translation, and essentially revert the translator's work.
```
> Fix #70: commited translations were not tagged as "committed".

- views/language.tpl
The UI's menu prominently lists "Languages" as a top-level menu item. Clicking a language from that page it shows the projects for that language. Then after clicking a project, I would expect to arrive at the overview page of that language for that project, however that currently navigates to the project page and I have (yet again) select the language I want to translate.
This PR changes that by eliminating this last step.
I haven't verified whether this change actually works, as I don't have a local checkout / working environment. Based on the template variables it seems fine to me, but needs an additional pair of eyes.
> Deeplink to language inside project

- .github/workflows/commit-checker.yml
- .github/workflows/publish.yml
- .github/workflows/testing.yml
- docs/manual/string_commands.rst
- webtranslate/parameter_info_table.py
[OpenTTD#10123](https://github.com/OpenTTD/OpenTTD/pull/10123) introduced `{POWER_TO_WEIGHT}` and strings using it are currently considered invalid.
Edit: workflows needed an update but I think I'll let @TrueBrain handle `deployment.yml` and `publish.yml`
> Fix #115: add support for {POWER_TO_WEIGHT} introduced by OpenTTD#10123

- webtranslate/pages/language_list.py
- webtranslate/pages/language_overview.py
- webtranslate/pages/upload_language.py
flake8 was complaining about use of `l` as a variable name. Fix that.
> Codechange: More descriptive variable names

- webtranslate/__main__.py
- webtranslate/config.py
- webtranslate/users/github.py
As GitHub is IPv4-only, sometimes there is a need to proxy GitHub via other domains to enable IPv6 connectivity. For those cases, these settings are useful.
> Add: allow defining the URL to use for GitHub for user authentication

- scripts/lang_sync
Cloudflare, rightfully, doesn't appreciate calls without a user-agent, and blocks the request.
> Fix: lang-sync doesn't send a user-agent

- webtranslate/pages/upload_language.py
Python 3 requires a `key=` parameter for `sorted()`. Been broken for a while...
> Fix: Upload language page raised 500 error due to syntax error

- webtranslate/bottle.py
Was trying to run eints locally, ran into the issue that `inspect.getargspec` has been deprecated and removed in Python 3.11, and a bottle update was required.
Retains existing modifications.
Additionally, while trying to set up eints to begin with, ran into the issue that my `rights.dat` file was empty (think it was generated like that?), resulting in `/login` being redirected to `/login` due to a lack of access rights. Not super helpful, so as this is always a configuration error, raise a fatal error here instead.
> Codechange: Update to bottle 0.12.25

- docs/manual/string_commands.rst
- webtranslate/parameter_info_table.py
OpenTTD/OpenTTD#11341 added 4 new string commands, which work like "number with unit":
* UNITS_DAYS_OR_SECONDS
* UNITS_MONTHS_OR_MINUTES
* UNITS_YEARS_OR_PERIODS
* UNITS_YEARS_OR_MINUTES
> Add: Support for time-unit parameters from OpenTTD#11341.

- docs/manual/string_commands.rst
Documentation display is broken
It's because the table is malformed
I fixed it using `reStructuredText` extension in vscode.
From the preview:
> Fix: Malformed table in string_commands.rst

- Dockerfile
Annotation checks failure because `Dockerfile:1 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match`
> Fix: Case inconsistency in Dockerfile

- docs/manual/string_commands.rst
- webtranslate/parameter_info_table.py
Fixes #200
The `{SPACE}` string code was added to strgen in OpenTTD#13149 to allow trailing spaces to be included in strings.
This is untested, I have no idea what I'm doing...
> Add: Support for SPACE from OpenTTD#13149

- scripts/eintsgit.py
By missing an extra newline, it meant that all the text was part of the title (just split over multiple lines). By adding an extra newline, it becomes clear to "git" that those lines are actually the body.
> Fix: contributors in commit message should be in the body, not title

- .github/workflows/testing.yml
- Dockerfile
- requirements.txt
This includes a dependency-bump, as it might add/remove polyfill libraries
> Upgrade: Bump Python to 3.11

- scripts/eintsgit.py
This also "solves" the problem, of `eintsgit` using `master` as default branch.
> Change: Disable git pull by default, github actions do that already.

- scripts/lang_sync
All our projects use en_GB as base language.
Avoid to set this in workflows.
> Change: Default base language to en_GB for first uploads.
